Issue-26: Update test_health.gd to use the cards, fix a big with Damage All card by adding EffectDamageAll.gd
Saplings-Projects/1M_sub pull request #41
Opened 2024-01-09 04:37 UTC by Tysterman74

# Description

Updated test_health.gd and added a few unit tests that test around using the actual cards in the Cards/Resource folder and test their effects. Fixed a bug with Damage All card.

## Related issue(s)

#26 

## List of changes

- Updated test_health.gd, added new unit tests that tests each card currently in Cards/Resource folder
- Added EffectDamageAll.gd to fix a bug of Damage All Card not working
- Added the new Effect to the Card_DamageAll.tres
- Updated the test scene to include in the Card_DamageAll in the default deck

## Tests

- Updated test_health.gd, added new unit tests that tests each card currently in Cards/Resource folder

## Additional notes

There may need to be an update to the poison tests since currently there hasn't been a decision on what the poison should be doing in terms of damage. Left a comment there to elaborate.

2024-01-09 14:34 UTC, Turtyo commented
I think we will have conflicts with #39 once merged because it changes DamageAll too iirc

2024-01-09 16:01 UTC, Turtyo requested changes
Not much to say, it looks clean :+1:

2024-01-09 16:01 UTC, Turtyo commented on Tests/test_health.gd
> +	var card_damage_and_poison: CardBase = load("res://Cards/Resource/Card_damage_and_poison.tres")
maybe adding the description of the card in the test would be good (so we don't need to go check the card)

2024-01-10 10:35 UTC, Turtyo approved these changes

2024-01-10 10:35 UTC, Turtyo commented on Tests/test_health.gd
> +# Test Card that deals 1 damage and applies poison to enemy and does poison damage on enemy turn
missing number of poison stack

2024-01-13 11:59 UTC, Turtyo approved these changes

2024-01-13 16:17 UTC, cheesefrycook approved these changes

2024-01-13 19:20 UTC, merged